### ISSUE TITLE
[BUG] - frequently stops popping up messages for outgoing and incoming traade requests

### ISSUE THREAD

**Issue by dyfrgi** [Morph21/MercuryTrade-Community-Fork#122]
After playing for a while, messages stop popping up. I haven't found a way to consistently trigger the bug, but once it starts it doesn't stop unless I restart MercuryTrade. That usually fixes the issue.

Here is an example outgoing log that didn't trigger a popup:
```
2022/06/02 14:54:19 956502984 cff9459d [INFO Client 34144] @To Tartinade: Hi, I would like to buy your Watcher's Eye Prismatic Jewel listed for 5 chaos in Sentinel (stash tab "~b/o 5 chaos"; position: left 7, top 20
```
And here is an incoming one:
```
2022/06/02 14:43:17 955841375 cff9459d [INFO Client 34144] @From Sanicx: Hi, I would like to buy your Inspired Learning Crimson Jewel listed for 2 exalted in Sentinel (stash tab "stuf"; position: left 10, top 1)
```

**Comment by orreuerro** [comment]
Same bug and every time same error in log file:
2022-06-13 17:07:05.635 [Thread-5] ERROR ErrorHandler - java.lang.IllegalArgumentException
	at java.util.Date.parse(Unknown Source)
	at java.util.Date.<init>(Unknown Source)
	at com.mercury.platform.core.utils.MessageFileHandler.lambda$parse$1(MessageFileHandler.java:81)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.mercury.platform.core.utils.MessageFileHandler.parse(MessageFileHandler.java:86)
	at com.mercury.platform.core.utils.FileMonitor$1.onFileChange(FileMonitor.java:43)
	at org.apache.commons.io.monitor.FileAlterationObserver.doMatch(FileAlterationObserver.java:412)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:335)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:305)
	at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:184)
	at java.lang.Thread.run(Unknown Source)

**Comment by Morph21** [comment]
@orreuerro can you paste here an example message which produces that error which is recorded in Client.txt file?

**Comment by Morph21** [comment]
@orreuerro sadly, I cannot reproduce that error. I tried yours and dyfrgi examples and they work for me :(

**Comment by Morph21** [comment]
```2022/06/15 20:33:57 31199953 3796fec6 [WARN Client 17836] Instant/Triggered action - Client failed to create aciton.```

that error is from path of exile so it can be because of dx12.

But MT not working is not related to dx12 since it "receives" messages from game only from that Client.txt file (It's the only way to get data from poe)

**Comment by dyfrgi** [comment]
Hmm so clearly it's happening when parsing a date, looking at that backtrace. So are the date formats in Client.txt somehow variable? Or maybe it's because of that multi-line log message. Can I get MercuryTrade to re-parse the file somehow? That would let us binary search our Client.txt for the cause.

**Comment by koko-fox** [comment]
Im into the same problem.
I think collect only the lines starting with 20xx/xx/xx.
