### ISSUE TITLE
Startup Problem with Linux

### ISSUE THREAD

**Issue by hosaka86** [Morph21/MercuryTrade-Community-Fork#40]
Hi,

I'm running on OpenJDK Runtime Environment (build 1.8.0_265-b01) and arch Linux. If i run java -jar MecuryTrade.jar I just get:

[main] ERROR ErrorHandler - java.lang.UnsupportedOperationException: This platform is not supported, yet.
	at com.sun.jna.platform.WindowUtils$NativeWindowUtils.getAllWindows(WindowUtils.java:659)
	at com.sun.jna.platform.WindowUtils.getAllWindows(WindowUtils.java:1980)
	at com.mercury.platform.AppMain.getGamePath(AppMain.java:78)
	at com.mercury.platform.AppMain.main(AppMain.java:47)

**Comment by Morph21** [comment]
Are you trying to run version 1.5.1 pre-relase with linux support?

**Comment by Morph21** [comment]
should work with this version https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.1.5.2

but you need java from official oracle site www.java.com/download
