### ISSUE TITLE
Issue on mac

### ISSUE THREAD

**Issue by bacoscaSergiu** [Morph21/MercuryTrade-Community-Fork#41]
When I run with java -jar MercuryTrade.jar

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:MercuryTrade.jar) to field java.awt.Color.value
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

It runs, I can select where the logs are, it does see the messages because it plays the notification sound but it does not create the notification window and pc freezes for few minutes.
--------------------------------------------------------------------------------

Tried several times, now while I was writing this I got a new error and the main windows does not appear anymore

13:47:41.103 [main] ERROR ErrorHandler - java.lang.NoClassDefFoundError: com/sun/awt/AWTUtilities
	at com.mercury.platform.ui.adr.components.AbstractAdrFrame.<init>(AbstractAdrFrame.java:31)
	at com.mercury.platform.ui.adr.components.AbstractAdrComponentFrame.<init>(AbstractAdrComponentFrame.java:23)
	at com.mercury.platform.ui.adr.components.AdrTrackerGroupFrame.<init>(AdrTrackerGroupFrame.java:18)
	at com.mercury.platform.ui.adr.components.factory.frame.TrackerGroupFrameProvider.getFrame(TrackerGroupFrameProvider.java:24)
	at com.mercury.platform.ui.adr.AdrManager.lambda$initComponents$11(AdrManager.java:297)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.mercury.platform.ui.adr.AdrManager.initComponents(AdrManager.java:283)
	at com.mercury.platform.ui.adr.AdrManager.load(AdrManager.java:63)
	at com.mercury.platform.ui.manager.FramesManager.start(FramesManager.java:147)
	at com.mercury.platform.AppMain.main(AppMain.java:65)
Caused by: java.lang.ClassNotFoundException: com.sun.awt.AWTUtilities
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 10 more
--------------------------------------------------------------------------------

This is the version of java I have
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**Comment by Morph21** [comment]
Can you try running it with oracle java installed from here? https://java.com/download/

**Comment by bacoscaSergiu** [comment]
Same thing, withouth the errors in terminal

**Comment by Morph21** [comment]
You can try the newest version: https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.1.5.2

And im not happy to say that but linux/macOS version won't be continued besides some critical bug fixes. You can read more about it here: https://github.com/Morph21/MercuryTrade-Community-Fork/wiki/Linux-macOS-not-working-manifest
