### ISSUE TITLE
[BUG] - NoClassDefFoundError - AWTUtilities - jdk-15.0.2

### ISSUE THREAD

**Issue by xiLight** [Morph21/MercuryTrade-Community-Fork#56]
**Describe the bug**

**To Reproduce**
1. Go to 'folder'
2. Click on 'MercuryTrade.jar'
3. Scroll down to '-'
4. See error: 

`15:38:33.611 [main] ERROR ErrorHandler - java.lang.NoClassDefFoundError: com/sun/awt/AWTUtilities
        at com.mercury.platform.ui.adr.components.AbstractAdrFrame.<init>(AbstractAdrFrame.java:32)
        at com.mercury.platform.ui.adr.components.AbstractAdrComponentFrame.<init>(AbstractAdrComponentFrame.java:23)
        at com.mercury.platform.ui.adr.components.AdrTrackerGroupFrame.<init>(AdrTrackerGroupFrame.java:18)
        at com.mercury.platform.ui.adr.components.factory.frame.TrackerGroupFrameProvider.getFrame(TrackerGroupFrameProvider.java:24)
        at com.mercury.platform.ui.adr.AdrManager.lambda$initComponents$11(AdrManager.java:297)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.mercury.platform.ui.adr.AdrManager.initComponents(AdrManager.java:283)
        at com.mercury.platform.ui.adr.AdrManager.load(AdrManager.java:63)
        at com.mercury.platform.ui.manager.FramesManager.start(FramesManager.java:150)
        at com.mercury.platform.AppMain.main(AppMain.java:66)
Caused by: java.lang.ClassNotFoundException: com.sun.awt.AWTUtilities
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 10 more`

**Expected behavior**
-

**Screenshots**
![image](https://user-images.githubusercontent.com/26903275/107234524-0d556800-6a24-11eb-9f0f-543b52308193.png)
![image](https://user-images.githubusercontent.com/26903275/107234556-17776680-6a24-11eb-8dd5-fe67d53d93b2.png)

**Desktop (please complete the following information):**
 - Version [LATEST]

**Additional context**
-

**Comment by Morph21** [comment]
yea, it's stated in readme that you need java from here:

![image](https://user-images.githubusercontent.com/38075691/107235804-59ed7300-6a25-11eb-8965-49bd8570b092.png)

https://java.com/download

**Comment by xiLight** [comment]
I also have this Version installed.

**Comment by xiLight** [comment]
![image](https://user-images.githubusercontent.com/26903275/107237793-696dbb80-6a27-11eb-8eff-3ba52626ca83.png)

**Comment by Morph21** [comment]
it's duplicate of this issue https://github.com/Morph21/MercuryTrade-Community-Fork/issues/31

**Comment by Morph21** [comment]
it's not sufficient to have 2 versions installed, you need to run .jar file with 1.8 java version, then it will work.

**Comment by xiLight** [comment]
Deleting local helped. Thx.
