### ISSUE TITLE
[BUG] - Permanently Loading app with annoying icon on center of screen

### ISSUE THREAD

**Issue by se7enek** [Morph21/MercuryTrade-Community-Fork#81]
``**Describe the bug**
Whenever i launch MercuryTrade, i got a loading icon on center of screen, permanently.

**To Reproduce**
1. Run MercuryTrade?

**Expected behavior**
Working Program

**Screenshots**
![image](https://user-images.githubusercontent.com/46325161/127733608-93658523-9da3-4d0d-bb65-b5dcb917add4.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/46325161/127733619-8500f661-895c-49e4-8d3d-1d9b4c12d324.png)
![image](https://user-images.githubusercontent.com/46325161/127733743-bb264aec-d830-42f3-bb6d-d1c4c84dc0d7.png)

**Logs**

```
2021-07-31 10:11:15.639 [main] ERROR ErrorHandler - java.lang.NoClassDefFoundError: com/sun/awt/AWTUtilities
	at com.mercury.platform.ui.adr.components.AbstractAdrFrame.<init>(AbstractAdrFrame.java:32)
	at com.mercury.platform.ui.adr.components.AbstractAdrComponentFrame.<init>(AbstractAdrComponentFrame.java:23)
	at com.mercury.platform.ui.adr.components.AdrTrackerGroupFrame.<init>(AdrTrackerGroupFrame.java:18)
	at com.mercury.platform.ui.adr.components.factory.frame.TrackerGroupFrameProvider.getFrame(TrackerGroupFrameProvider.java:24)
	at com.mercury.platform.ui.adr.AdrManager.lambda$initComponents$11(AdrManager.java:297)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at com.mercury.platform.ui.adr.AdrManager.initComponents(AdrManager.java:283)
	at com.mercury.platform.ui.adr.AdrManager.load(AdrManager.java:63)
	at com.mercury.platform.ui.manager.FramesManager.start(FramesManager.java:150)
	at com.mercury.platform.AppMain.main(AppMain.java:66)
Caused by: java.lang.ClassNotFoundException: com.sun.awt.AWTUtilities
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 10 more```

**Comment by se7enek** [comment]
![image](https://user-images.githubusercontent.com/46325161/127733792-3df02ed1-1540-4271-8f9a-a7a3081f12e1.png)
updated java but still same thing.

**Comment by krissrex** [comment]
What is your operating system?
Are you sure Mercury is run with java 8? Do you also have java 11 installed, or some other version?

**Comment by se7enek** [comment]
Bump
[https://streamable.com/7go8a5](https://streamable.com/7go8a5)

**Comment by conixtract** [comment]
Did you find a solution to this issue?

**Comment by Morph21** [comment]
Install oracle java from https://java.com/pl/download/
