### ISSUE TITLE
[BUG] - Stuck on loading screen.

### ISSUE THREAD

**Issue by NokTham** [Morph21/MercuryTrade-Community-Fork#89]
Tried to create a shortcut with the target "C:\Program Files\Java\jdk-16.0.2\bin\javaw.exe" --illegal-access=permit -jar MercuryTrade.jar but got the same result.

15:18:22.506 [main] ERROR ErrorHandler - java.lang.NoClassDefFoundError: com/sun/awt/AWTUtilities
        at com.mercury.platform.ui.adr.components.AbstractAdrFrame.<init>(AbstractAdrFrame.java:32)
        at com.mercury.platform.ui.adr.components.AbstractAdrComponentFrame.<init>(AbstractAdrComponentFrame.java:23)
        at com.mercury.platform.ui.adr.components.AdrTrackerGroupFrame.<init>(AdrTrackerGroupFrame.java:18)
        at com.mercury.platform.ui.adr.components.factory.frame.TrackerGroupFrameProvider.getFrame(TrackerGroupFrameProvider.java:24)
        at com.mercury.platform.ui.adr.AdrManager.lambda$initComponents$11(AdrManager.java:297)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.mercury.platform.ui.adr.AdrManager.initComponents(AdrManager.java:283)
        at com.mercury.platform.ui.adr.AdrManager.load(AdrManager.java:63)
        at com.mercury.platform.ui.manager.FramesManager.start(FramesManager.java:150)
        at com.mercury.platform.AppMain.main(AppMain.java:66)
Caused by: java.lang.ClassNotFoundException: com.sun.awt.AWTUtilities
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 10 more

---------------

Windows 10 LTSC
Java 16.0.2 - Also tried with Java 8.

**Comment by NokTham** [comment]
Had to uninstall Java 16 SDK in order to force it to use Java 8.

Seems to be running.
